Spawn:
  X: 4631.5
  Y: 154.0
  Z: -5014.5
  yaw: -90.0
  World: world
FFA:
  X: 4368.5
  Y: 185.0
  Z: -5034.5
  yaw: 0.0
  World: world
flat:
  X: 4517.5
  Y: 111.0
  Z: -4734.5
  yaw: 0.0
  World: world
sword:
  X: 4448.5
  Y: 99
  Z: -5284.5
  yaw: 0.0
  World: world
underwater:
  X: 30.5
  Y: 33.0
  Z: -9.5
  yaw: 0.0
  World: world