take-anti-lag-measures-if-tps: 14
disable-the-use-of-packet-elytra-fly: true
item-frame-dupe: false
item-frame-dupe-rng: 5
anti-illegals: true
illegal-items: true
overstacked-items: true
illegal-enchants: true
check-in-shulker-box: true

better-chat: true
better-chat-cooldown: 1

anti-bookban: true
anti-netherroof: true
anti-burrow: true

discord-link: https://discord.gg/example

no-death-messages: false
no-join-messages: false
no-quit-messages: false

tablist-header: "&7&o&l2BUILDERS\n&7&o&l2TOOLS      \n"
tablist-footer: "\n%tps% &7TPS - %players% players - %ping%&7ms"

randommotdenabled: true
motd:
    - "&7&o2BUILDERS 2TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
    - "&6&o5BUILDERS 5TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
    - "&c&o9BUILDERS 9TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
    - "&a&o8BUILDERS 8TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"

admin-whitelist:
    - "bigmilkercock"
    - "Catto69420"
    - "SFTB_"
    - "Bye"

auto-restart: false
auto-restart-minutes: 360

tpa: true
home: true