# takes action if tps is under 14
take-anti-lag-measures-if-tps: 14

# disables the use of infinite durability elytra flight
disable-the-use-of-packet-elytra-fly: true
# enables frame dupe
item-frame-dupe: false
# frame dupes chance
item-frame-dupe-rng: 5
# enables salc1's donkey dupe
salc1-donkey-dupe: false
# enables anti illegals system
chest-limit-per-chunk: true
anti-illegals: true
illegal-items: true
overstacked-items: true
illegal-enchants: true
check-in-shulker-box: true

better-chat: true
better-chat-cooldown: 1

anti-bookban: true
anti-netherroof: true
anti-burrow: true

discord-link: https://discord.gg/example

no-death-messages: false
no-join-messages: false
no-quit-messages: false

# tab list customization
tablist-header: "&7&o&l2BUILDERS\n&7&o&l2TOOLS    \n"
tablist-footer: "\n%tps% &7TPS - %players% players - %ping% &7ping"

# random motd
randommotdenabled: true
motd:
    - "&7&o&l2BUILDERS 2TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
    - "&6&o&l5BUILDERS 5TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
    - "&4&o&l9BUILDERS 9TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
    - "&2&o&l8BUILDERS 8TOOLS\n&7Current TPS: %tps% &e----- &7Current Player count: %players%"
# whitelist for /d command
admin-whitelist:
    - "bigmilkercock"
    - "Catto69420"

auto-restart: false
auto-restart-minutes: 360

tpa: true
home: true