ShouldTeleportPlayerToSpawn: true
placeholders:
  discordlink: https://discord.gg/aestheticnetwork

discordmessage: You can join our discord server using
Spawn:
  X: 51.5
  Y: 116.0
  Z: 369.5
  World: world
Arena: false
ArenaResetTimeInTicks: 26000
ArenaName: pvpline