name: Anarchy
version: 1.0.4
main: bab.bbb.Bbb
api-version: 1.19

commands:
  discord:
    description: Show the discord link
    usage: /<command>
    aliases: d
  tpa:
    description: Send a teleport request to a player.
    usage: /<command>
    aliases: [tpask ]
  tpahere:
    description: Send a teleport here request to a player.
    usage: /<command>
  tpaccept:
    description: Accept a teleport request.
    usage: /<command>
    aliases: [tpyes, tpy]
  tpdeny:
    description: Deny a teleport request.
    usage: /<command>
    aliases: [tpno, tpn]
  nick:
    description: Set a nickname.
    usage: /<command>
    aliases: [nickname]
  msg:
    description: Send message to a player.
    usage: /<command>
    aliases: [ whisper, tell ]
  secure:
    description: Secure your account from being accessed by others.
    usage: /<command>
    aliases: [ reg ]
  delhome:
    description: Delete the specified home.
    usage: /<command>
  home:
    description: Teleport to your home(s).
    usage: /<command>
  sethome:
    description: Set your home location.
    usage: /<command>
  reply:
    description: Reply to a player.
    usage: /<command>
    aliases: [ r ]
  ignore:
    description: Ignore a player.
    usage: /<command>
  kill:
    description: Suicide.
    usage: /<command>
    aliases: [ suicide ]