name: AestheticNetwork
version: '${project.version}'
main: main.Practice
api-version: 1.18

commands:
  spawn:
    usage: /<command>
  discord:
    usage: /<command>
    aliases: dc
  ffa:
    usage: /<command>
    aliases: [ hole, field ]
  flat:
    usage: /<command>
  tpa:
    usage: /<command>
    aliases: tpr
  tpahere:
    usage: /<command>
  tpdeny:
    usage: /<command>
    aliases: [ tpd, tpno ]
  tpaccept:
    usage: /<command>
    aliases: [ tpy, tpyes ]
  duel:
    usage: /<command>
    aliases: 1v1
  dueldeny:
    usage: /<command>
  duelaccept:
    usage: /<command>
  event:
    usage: /<command>
  msg:
    usage: /<command>
    aliases: [ tell, whisper, w, t ]
  reply:
    usage: /<command>
    aliases: r
  report:
    usage: /<command>
  killeffect:
    aliases: shop
    usage: /<command>
  msglock:
    usage: /<command>
    aliases: [ msgtoggle, togglemsg ]
  tpalock:
    usage: /<command>
    aliases: [ tpatoggle, toggletpa ]
  back:
    usage: /<command>
  help:
    usage: /<command>
  acreate:
    usage: /<command>
  rtp:
    usage: /<command>
  gmc:
    usage: /<command>
  gms:
    usage: /<command>
  kickall:
    usage: /<command>
  list:
    usage: /<command>
  ban:
    usage: /<command>
  unban:
    usage: /<command>
  vanish:
    aliases: v
    usage: /<command>
  warp:
    usage: /<command>
  setwarp:
    usage: /<command>
  tp:
    usage: /<command>
  tphere:
    usage: /<command>
  ss:
    usage: /<command>
  irename:
    usage: /<command>
    aliases: itemrename
  k1:
    usage: /<command>
    aliases: kit1
  k2:
    usage: /<command>
    aliases: kit2
  k3:
    usage: /<command>
    aliases: kit3
  kit:
    usage: /<command>
permissions:
  has.staff:
    description: Is a staff member