name: CatSMP
version: '${project.version}'
main: main.Economy
api-version: 1.19
depend:
  - ViaVersion
  - ViaBackwards
  - Vault
  - Essentials

commands:
  spawn:
    usage: /<command>
  discord:
    usage: /<command>
    aliases: dc
  tpa:
    usage: /<command>
    aliases: tpr
  tpahere:
    usage: /<command>
  tpdeny:
    usage: /<command>
    aliases: [ tpd, tpno ]
  tpaccept:
    usage: /<command>
    aliases: [ tpy, tpyes ]
  msg:
    usage: /<command>
    aliases: [ tell, whisper, w, t ]
  reply:
    usage: /<command>
    aliases: r
  tpaall:
    aliases: tpall
    usage: /<command>
  report:
    usage: /<command>
  msglock:
    usage: /<command>
    aliases: [ msgtoggle, togglemsg ]
  tpalock:
    usage: /<command>
    aliases: [ tpatoggle, toggletpa ]
  rbalance:
    uasge: /<command>
    aliases: rbal
  warp:
    usage: /<command>
  setwarp:
    usage: /<command>
  rtp:
    usage: /<command>
    aliases: wild
  playtime:
    usage: /<command>
  kit:
    usage: /<command>
  ec:
    aliases: [ enderchest, echest ]
    uasge: /<command>
  setrank:
    usage: /<command>
  rgc:
    usage: /<command>
  grindstone:
    usage: /<command>
  list:
    usage: /<command>
  broadcast:
    aliases: bc
    usage: /<command>
  bombrtp:
    usage: /<command>
  banip:
    uasge: /<command>
  suicide:
    usage: /<command>
    aliases: kill
  fastcrystals:
    usage: /<command>
  irename:
    usage: /<command>
    aliases: [ name, iname, itemname, itemrename ]