name: AestheticNetwork
version: '${project.version}'
main: org.yuri.aestheticnetwork.AestheticNetwork
api-version: 1.18

commands:
  spawn:
    usage: /<command>
  discord:
    usage: /<command>
  ffa:
    usage: /<command>
    aliases: [ hole, field ]
  flat:
    usage: /<command>
  tpa:
    usage: /<command>
    aliases: tpr
  tpahere:
    usage: /<command>
  tpdeny:
    usage: /<command>
    aliases: [ tpd, tpno ]
  tpaccept:
    usage: /<command>
    aliases: [ tpy, tpyes ]
  msg:
    usage: /<command>
    aliases: [ tell, whisper, w, t ]
  reply:
    usage: /<command>
    aliases: r
  report:
    usage: /<command>
  shop:
    usage: /<command>
  msglock:
    usage: /<command>
    aliases: [ msgtoggle, togglemsg ]
  tpalock:
    usage: /<command>
    aliases: [ tpatoggle, toggletpa ]
  duel:
    usage: /<command>
    aliases: 1v1
  duelaccept:
    usage: /<command>
  dueldeny:
    usage: /<command>
  event:
    usage: /<command>
  back:
    usage: /<command>
  help:
    usage: /<command>
permissions:
  has.staff:
    description: Is a staff member