name: AestheticNetwork
version: '${project.version}'
main: main.AestheticNetwork
api-version: 1.18

commands:
  spawn:
    usage: /<command>
  discord:
    usage: /<command>
  ffa:
    usage: /<command>
    aliases: [ hole, field ]
  flat:
    usage: /<command>
  tpa:
    usage: /<command>
    aliases: tpr
  tpahere:
    usage: /<command>
  tpdeny:
    usage: /<command>
    aliases: [ tpd, tpno ]
  tpaccept:
    usage: /<command>
    aliases: [ tpy, tpyes ]
  msg:
    usage: /<command>
    aliases: [ tell, whisper, w, t ]
  reply:
    usage: /<command>
    aliases: r
  report:
    usage: /<command>
  shop:
    usage: /<command>
  msglock:
    usage: /<command>
    aliases: [ msgtoggle, togglemsg ]
  tpalock:
    usage: /<command>
    aliases: [ tpatoggle, toggletpa ]
  back:
    usage: /<command>
  help:
    usage: /<command>
  kit:
    aliases: k
    usage: /<command>
  kit1:
    aliases: k1
    usage: /<command>
  kit2:
    aliases: k2
    usage: /<command>
  kit3:
    aliases: k3
    usage: /<command>
permissions:
  has.staff:
    description: Is a staff member