name: AestheticNetwork
version: '${project.version}'
main: org.yuri.eco.AestheticNetwork
api-version: 1.19
depend: [Vault, LuckPerms]

commands:
  spawn:
    description: Teleports you to spawn
    usage: /<command>
  discord:
    description: Displays the discord link
    usage: /<command>
  tpa:
    usage: /<command>
    aliases: tpr
  tpahere:
    usage: /<command>
  tpdeny:
    usage: /<command>
    aliases: [ tpd, tpno ]
  tpaccept:
    usage: /<command>
    aliases: [ tpy, tpyes ]
  msg:
    usage: /<command>
    aliases: [ tell, whisper, w, t ]
  reply:
    usage: /<command>
    aliases: r
  tpaall:
    usage: /<command>
  report:
    usage: /<command>
  chatlock:
    usage: /<command>
  msglock:
    usage: /<command>
    aliases: [ msgtoggle, togglemsg ]
  tpalock:
    usage: /<command>
    aliases: [ tpatoggle, toggletpa ]
  ebaltop:
    usage: /<command>
  stats:
    usage: /<command>
    aliases: statistics
permissions:
  has.staff:
    description: Use chatlock & Bypass it
  coloranvils.use:
    description: Use colored anvils