name: CatSMP
version: '${project.version}'
main: main.Economy
api-version: 1.19
depend:
  - ViaVersion
  - ViaBackwards
  - Vault

commands:
  spawn:
    usage: /<command>
  discord:
    usage: /<command>
    aliases: dc
  tpa:
    usage: /<command>
    aliases: tpr
  tpahere:
    usage: /<command>
  tpdeny:
    usage: /<command>
    aliases: [ tpd, tpno ]
  tpaccept:
    usage: /<command>
    aliases: [ tpy, tpyes ]
  msg:
    usage: /<command>
    aliases: [ tell, whisper, w, t ]
  reply:
    usage: /<command>
    aliases: r
  tpaall:
    aliases: tpall
    usage: /<command>
  report:
    usage: /<command>
  msglock:
    usage: /<command>
    aliases: [ msgtoggle, togglemsg ]
  tpalock:
    usage: /<command>
    aliases: [ tpatoggle, toggletpa ]
  stats:
    usage: /<command>
    aliases: statistics
  rbalance:
    uasge: /<command>
    aliases: rbal
  warp:
    usage: /<command>
  setwarp:
    usage: /<command>
  rtp:
    usage: /<command>
    aliases: wild
  rsethome:
    usage: /<command>
  rhome:
    usage: /<command>
  rdelhome:
    usage: /<command>
  playtime:
    usage: /<command>
  kit:
    usage: /<command>
  acreate:
    usage: /<command>
  enderchest:
    aliases: [ ec, echest ]
    uasge: /<command>
  setrank:
    usage: /<command>
  rgc:
    usage: /<command>
  rpay:
    usage: /<command>
  rbaltop:
    usage: /<command>
  anvil:
    usage: /<command>
  grindstone:
    usage: /<command>
  list:
    usage: /<command>
  broadcast:
    aliases: bc
    usage: /<command>
  bombrtp:
    usage: /<command>
  banip:
    uasge: /<command>